import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeftRight, RefreshCw, Play, Pause, Settings, Radio, CheckCircle2, AlertCircle } from 'lucide-react';
import type { Config, Opportunity, Position, State } from './types';

const ProfitChart = lazy(() => import('./ProfitChart'));
const format = (n: number | null | undefined, digits = 2) => n === null || n === undefined || !Number.isFinite(n) ? '—' : n.toLocaleString('zh-CN', { minimumFractionDigits: digits, maximumFractionDigits: digits });
const time = (value: number | null | undefined) => value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '等待数据';
const venues: Record<string, string> = { binance: 'Binance', bybit: 'Bybit', okx: 'OKX', gate: 'Gate', kraken: 'Kraken', hyperliquid: 'Hyperliquid', lighter: 'Lighter' };
const venue = (name: string) => venues[name] || name;
const direction = (row: { long: { exchange: string }; short: { exchange: string } }) => `${venue(row.long.exchange)} 做多 → ${venue(row.short.exchange)} 做空`;
const stateLabel = (state: string) => ({ live: '已连接', partial: '部分行情可用', offline: '未连接', stale: '数据过期', cached: '使用缓存', unavailable: '等待连接', connecting: '连接中', error: '连接异常', disabled: '未启用' }[state] || state);
type Tab = 'opportunities' | 'positions' | 'history' | 'settings';
const tabs: [Tab, string][] = [['opportunities', '发现机会'], ['positions', '模拟持仓'], ['history', '记录与收益'], ['settings', '连接与设置']];

export default function App() {
  const [state, setState] = useState<State | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [online, setOnline] = useState(false);
  const [tab, setTab] = useState<Tab>(() => tabs.some(x => x[0] === location.hash.slice(1)) ? location.hash.slice(1) as Tab : 'opportunities');
  const [selectedVenue, setSelectedVenue] = useState('');
  const [search, setSearch] = useState(''), [showAll, setShowAll] = useState(false), [now, setNow] = useState(Date.now());
  const requests = useRef(new Map<string, string>());
  const refresh = useCallback(async (signal?: AbortSignal) => {
    try { const res = await fetch('/api/state', { signal, cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setState(data); setOnline(true); }
    catch (e) { if (signal?.aborted) return; setOnline(false); setError(e instanceof Error ? e.message : '模块连接失败'); }
  }, []);
  useEffect(() => {
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    const poll = async () => { setNow(Date.now()); if (!document.hidden) await refresh(controller.signal); if (!controller.signal.aborted) timer = setTimeout(poll, 5000); };
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [refresh]);
  useEffect(() => { const change = () => { const hash = location.hash.slice(1); if (tabs.some(x => x[0] === hash)) setTab(hash as Tab); }; addEventListener('hashchange', change); return () => removeEventListener('hashchange', change); }, []);
  async function mutate(route: string, input: object, method = 'POST', actionKey?: string) {
    if (!state) return;
    setBusy(true); setError('');
    try {
      if (actionKey && !requests.current.has(actionKey)) {
        const id = typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : Array.from(crypto.getRandomValues(new Uint8Array(24)), n => n.toString(16).padStart(2, '0')).join('');
        requests.current.set(actionKey, id);
      }
      const res = await fetch(route, { method, headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': state.csrfToken }, body: JSON.stringify({ ...input, ...(actionKey ? { requestId: requests.current.get(actionKey) } : {}) }) });
      const data = await res.json(); if (!res.ok) throw new Error(data.error);
      if (actionKey) requests.current.delete(actionKey); await refresh(); return true;
    } catch (e) { setError(e instanceof Error ? e.message : '响应未确认，可重试相同操作；成功的请求不会重复记账'); return false; }
    finally { setBusy(false); }
  }
  const go = (value: Tab) => { setTab(value); location.hash = value; setError(''); };
  const stale = !online || !state?.source.updatedAt || now - state.source.updatedAt > 10000 || !['live', 'partial'].includes(state.source.state);
  const rows = state?.opportunities.filter(x => (showAll || x.eligible) && (!selectedVenue || [x.long.exchange, x.short.exchange].includes(selectedVenue)) && x.base.includes(search.trim().toUpperCase())) || [];
  return <div className="app">
    <header className="topbar"><div className="brand"><span className="brand-icon"><ArrowLeftRight size={25}/></span><div><h1>Gate CrossEx <span className="tag">模拟</span></h1><p>永续价差 · 发现到执行</p></div></div><div className="header-actions"><button disabled={busy} onClick={() => { setError(''); void refresh(); }} aria-label="刷新模块"><RefreshCw size={16}/><span>刷新</span></button><button className={state?.config.enabled ? '' : 'primary'} disabled={!state || busy || !online} onClick={() => void mutate('/api/settings', { config: { enabled: !state?.config.enabled } }, 'PUT')}>{state?.config.enabled ? <Pause size={16}/> : <Play size={16}/>} {state?.config.enabled ? '暂停自动模拟' : '启动自动模拟'}</button></div></header>
    <nav aria-label="模块功能">{tabs.map(([id, label]) => <button key={id} aria-current={tab === id ? 'page' : undefined} onClick={() => go(id)}>{label}{id === 'positions' && !!state?.totals.openCount && <span className="count">{state.totals.openCount}</span>}</button>)}</nav>
    <main><div className="context-line"><span><span className={`status-dot ${state?.config.enabled && !stale ? 'live' : ''}`}/>{state?.config.enabled ? stale ? '自动模拟等待行情' : '自动模拟运行中' : '自动模拟已暂停'}</span><span>仅模拟记账 · 不发送真实订单</span><span>北京时间</span></div>
      {error && <div role="alert" className="notice error"><AlertCircle size={18}/><span>{error}</span><button onClick={() => setError('')} aria-label="关闭提示">×</button></div>}
      {!state ? <div className="empty panel">正在读取模块状态…</div> : <>
        <section className="metrics" aria-label="模拟概览"><Metric label="已实现模拟盈亏" value={format(state.totals.realizedPnl)} unit="USDT" detail="累计平仓 · 已扣手续费，未含资金费" signed={state.totals.realizedPnl}/><Metric label="浮动模拟盈亏" value={format(stale && state.totals.openCount ? null : state.totals.unrealizedPnl)} unit="USDT" detail={state.totals.stalePositions ? `${state.totals.stalePositions} 组估值过期` : '按平仓方向盘口估值，包含预计平仓费'} signed={state.totals.unrealizedPnl}/><Metric label="模拟持仓" value={String(state.totals.openCount)} unit={`/ ${state.config.maxOpen} 组`} detail={`双腿占用 ${format(state.totals.usedNotional)} / ${format(state.config.maxTotalNotional, 0)} USDT`}/></section>
        <section className="connections" aria-label="数据来源"><div><Radio size={18}/><span><strong>Market Monitor</strong><span className={stale ? 'warning' : 'positive'}>{stale ? stateLabel(state.source.state === 'live' ? 'stale' : state.source.state) : stateLabel(state.source.state)}</span><small>行情源时间 {time(state.source.updatedAt)}</small></span></div><div><CheckCircle2 size={18}/><span><strong>CrossEx 合约目录</strong><span className={state.catalog.state === 'live' ? 'positive' : 'warning'}>{stateLabel(state.catalog.state)}</span><small>核对时间 {time(state.catalog.updatedAt)}</small></span></div>{(state.source.error || state.catalog.error) && <p className="connection-error">{state.source.error || state.catalog.error}<button className="text-button" onClick={() => go('settings')}>检查连接 <Settings size={13}/></button></p>}</section>
        <section className="coverage" aria-label="交易所与汇率"><div className="venue-strip">{state.venues?.map(item => <span key={item.id}><strong>{venue(item.id)}</strong><small className={item.state === 'live' ? 'positive' : 'warning'}>{stateLabel(item.state)} · {item.quoteCount} 个合约</small></span>)}</div><div className="fx-strip">{state.fx?.map(item => <span key={item.currency}>{item.currency} / USDT {item.state === 'live' ? `${format(item.bid, 6)} / ${format(item.ask, 6)} · ${time(item.at)}` : '汇率待更新，该币种暂不模拟'}</span>)}</div></section>
        {tab === 'opportunities' && <section className="panel"><div className="section-heading"><div><h2>同币种，跨所价差</h2><p>七所永续 · 统一折算 USDT · {state.opportunities.filter(x => x.eligible).length} 个候选通过初筛</p></div><div className="filters"><select aria-label="筛选交易所" value={selectedVenue} onChange={e => setSelectedVenue(e.target.value)}><option value="">全部交易所</option>{Object.entries(venues).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select><input aria-label="搜索币种" placeholder="搜索币种" value={search} onChange={e => setSearch(e.target.value)}/><label className="check"><input type="checkbox" checked={showAll} onChange={e => setShowAll(e.target.checked)}/>显示未通过机会</label></div></div><div className="table-wrap"><table><thead><tr><th>币种 / 方向</th><th>多腿卖一 / 空腿买一</th><th>折算毛价差</th><th>预算净价差</th><th>检查结果</th><th>操作</th></tr></thead><tbody>{rows.slice(0, 100).map(row => <OpportunityRow key={row.pairKey} row={row} disabled={busy || stale} open={() => void mutate('/api/open', { signalId: row.id }, 'POST', `open:${row.id}`)}/>)}</tbody></table></div>{!rows.length && <div className="empty"><ArrowLeftRight size={28}/><h3>{stale ? '等待价差模块的实时信号' : '暂时没有达到阈值的机会'}</h3><p>{stale ? '在连接与设置中填写同机价差服务的登录信息。' : '可显示未通过机会查看原因，或在设置里调整模拟参数。'}</p></div>}<div className="footnote">盘口价格保留原计价币；价差按双边汇率折算 USDT。1 bp = 0.01%。预算净价差 = 盘口毛价差 − 四次手续费 − 四次滑点预算。点击开仓后重新读取双腿深度，按滑点上限与 CrossEx 数量规则复核。</div></section>}
        {tab === 'positions' && <section className="panel"><div className="section-heading"><div><h2>模拟持仓</h2><p>启动自动模拟后按止盈、止损或持有时限平仓；暂停同时停止自动开仓和平仓。</p></div></div>{state.positions.length ? <div className="positions">{state.positions.map(p => <PositionCard key={p.id} p={p} stale={stale} disabled={busy || !online} close={() => void mutate('/api/close', { positionId: p.id }, 'POST', `close:${p.id}`)}/>)}</div> : <div className="empty"><h3>还没有模拟持仓</h3><p>从机会中手动开仓，或开启自动模拟。</p></div>}</section>}
        {tab === 'history' && <><section className="panel"><div className="section-heading"><div><h2>已实现模拟盈亏</h2><p>实际模拟平仓记录累计，单位 USDT；未包含资金费。</p></div></div>{state.history.length ? <Suspense fallback={<div className="empty">加载曲线…</div>}><ProfitChart positions={state.history} total={state.totals.realizedPnl}/></Suspense> : <div className="empty">平仓后显示收益曲线</div>}<div className="table-wrap"><table><thead><tr><th>币种 / 方向</th><th>开仓 / 平仓时间</th><th>数量</th><th>总手续费</th><th>净盈亏 USDT</th><th>平仓原因</th></tr></thead><tbody>{state.history.map(p => <tr key={p.id}><td><strong>{p.base}</strong><small>{direction(p)}</small></td><td>{time(p.openedAt)}<small>{time(p.closedAt)}</small></td><td>{format(p.quantity, 8)}</td><td>{format(p.entryFees + (p.result?.exitFees || 0), 4)}</td><td className={(p.result?.net || 0) < 0 ? 'negative' : 'positive'}>{format(p.result?.net, 4)}</td><td>{p.reason}</td></tr>)}</tbody></table></div><div className="footnote">显示最近 200 笔；累计盈亏包含所有已保存的平仓记录。</div></section><section className="panel event-panel"><h2>运行记录</h2>{state.events.map((e, i) => <div className="event" key={`${e.at}:${i}`}><time>{time(e.at)}</time><span>{e.message}</span></div>)}{!state.events.length && <p className="muted">暂无操作记录</p>}</section></>}
        {tab === 'settings' && <SettingsForm config={state.config} busy={busy} save={value => mutate('/api/settings', value, 'PUT')}/>}
        <p className="model-note">模拟模型：双腿在可见深度内都能全量成交才记账，均价包含逐档滑点。同币种等量对冲未覆盖汇率风险；Hyperliquid 的 USDT 报价合约以 USDC 结算。未模拟实盘的排队、延迟、单腿成交、强平和资金费；结果不能视为可实现收益。无需交易所 API Key。</p>
      </>}
    </main></div>;
}
function Metric({ label, value, unit, detail, signed }: { label: string; value: string; unit: string; detail: string; signed?: number | null }) { return <div className="metric"><span>{label}</span><div className={signed === undefined || signed === null || value === '—' ? '' : signed < 0 ? 'negative' : 'positive'}><strong>{value}</strong><small>{unit}</small></div><p>{detail}</p></div>; }
function OpportunityRow({ row, disabled, open }: { row: Opportunity; disabled: boolean; open: () => void }) { return <tr><td><strong>{row.base}</strong><small>{direction(row)}</small></td><td>{format(row.long.ask, 6)} {row.long.quoteCurrency}<small>{format(row.short.bid, 6)} {row.short.quoteCurrency}</small></td><td>{format(row.grossBps)} bp</td><td className={(row.netBps || 0) > 0 ? 'positive' : ''}>{format(row.netBps)} bp</td><td><span className={row.eligible ? 'positive' : 'muted'}>{row.eligible ? '待深度复核' : row.reason}</span>{!!row.warnings?.length && <small className="rule-note">部分目录额度未提供，仅按模拟预算复核</small>}</td><td><button className="primary" disabled={disabled || !row.eligible} onClick={open}>模拟开仓</button></td></tr>; }
function PositionCard({ p, stale, disabled, close }: { p: Position; stale: boolean; disabled: boolean; close: () => void }) { return <article className="position"><div className="position-title"><div><h3>{p.base} <span className="tag">双腿模拟持仓</span></h3><p>{direction(p)}</p></div><button onClick={close} disabled={disabled}>模拟平仓</button></div><dl><div><dt>每腿基础币数量</dt><dd>{format(p.quantity, 8)}</dd></div><div><dt>多腿 / 空腿开仓均价</dt><dd>{format(p.longFill.price, 6)} {p.long.quoteCurrency || 'USDT'} / {format(p.shortFill.price, 6)} {p.short.quoteCurrency || 'USDT'}</dd></div><div><dt>预计净盈亏 USDT</dt><dd className={p.valuation.stale || stale ? 'warning' : (p.valuation.net || 0) < 0 ? 'negative' : 'positive'}>{format(p.valuation.net, 4)}{(p.valuation.stale || stale) && ' · 旧估值'}</dd></div><div><dt>开仓时间</dt><dd>{time(p.openedAt)}</dd></div></dl><small className="muted">估值时间 {time(p.valuation.at)} · 平仓重新检查真实深度</small><p className="settlement-note">结算币：多腿 {p.long.settlementCurrency || p.long.quoteCurrency || 'USDT'} / 空腿 {p.short.settlementCurrency || p.short.quoteCurrency || 'USDT'}；收益按结算时汇率折算 USDT</p>{!!p.unverifiedConstraints?.length && <details className="settlement-note"><summary>部分目录规则未提供</summary>{p.unverifiedConstraints.map(note => <p key={note}>{note}</p>)}</details>}</article>; }
function SettingsForm({ config, busy, save }: { config: Config; busy: boolean; save: (input: object) => Promise<boolean | undefined> }) {
  const [draft, setDraft] = useState(() => { const { hasMonitorPassword: _, ...value } = config; return value; }), [password, setPassword] = useState(''), [clear, setClear] = useState(false), [saved, setSaved] = useState(false);
  useEffect(() => { setDraft(value => ({ ...value, enabled: config.enabled })); }, [config.enabled]);
  const numeric: [keyof Config, string, string][] = [['notionalPerLeg', '单腿名义额', 'USDT'], ['maxTotalNotional', '双腿总名义额上限', 'USDT'], ['maxOpen', '最多同时持仓', '组'], ['feeBps', '每次成交手续费', 'bp'], ['slippageBps', '每次成交滑点上限', 'bp'], ['minNetBps', '最低预算净价差', 'bp'], ['takeProfitBps', '止盈 / 单腿开仓额', 'bp'], ['stopLossBps', '止损 / 单腿开仓额', 'bp'], ['maxHoldMinutes', '最长持有', '分钟'], ['cooldownSeconds', '同币种平仓后冷却', '秒']];
  return <form onSubmit={async e => { e.preventDefault(); setSaved(false); if (await save({ config: draft, ...(password ? { monitorPassword: password } : {}), clearMonitorPassword: clear })) { setSaved(true); setPassword(''); setClear(false); } }}><section className="panel settings-panel"><h2>价差服务连接</h2><p className="muted">填写 Market Monitor 的网页登录信息，密码仅加密保存在此模块服务器。</p><div className="form-grid"><label>同机服务地址<input required value={draft.monitorUrl} onChange={e => setDraft({ ...draft, monitorUrl: e.target.value })}/></label><label>登录用户名<input value={draft.monitorUsername} autoComplete="off" onChange={e => setDraft({ ...draft, monitorUsername: e.target.value })}/></label><label>登录密码<input type="password" value={password} autoComplete="new-password" placeholder={config.hasMonitorPassword ? '已保存，留空保留' : '尚未保存'} onChange={e => setPassword(e.target.value)}/></label></div><label className="check"><input type="checkbox" checked={clear} onChange={e => setClear(e.target.checked)}/>清除已保存的价差服务密码</label><p className="footnote">更换地址或用户名会清除旧密码。修改后的 Monitor 需要提供机会接口；默认地址为 http://127.0.0.1:3000。</p></section><section className="panel settings-panel"><h2>模拟策略参数</h2><p className="muted">手续费是模拟假设，不代表你的 CrossEx 账户费率。参数变更仅影响后续开仓，已有持仓保留开仓时的平仓规则。</p><div className="form-grid">{numeric.map(([key, label, unit]) => <label key={key}>{label}<div className="input-unit"><input required type="number" step={key === 'maxOpen' ? '1' : 'any'} value={Number(draft[key as keyof typeof draft])} onChange={e => setDraft({ ...draft, [key]: Number(e.target.value) })}/><span>{unit}</span></div></label>)}</div><label className="check"><input type="checkbox" checked={draft.enabled} onChange={e => setDraft({ ...draft, enabled: e.target.checked })}/>启用自动模拟开仓与平仓</label><div className="save-row"><button className="primary" disabled={busy} type="submit">保存设置</button>{saved && <span role="status" className="positive">已保存</span>}</div></section></form>;
}
